name: Wolfram's workflow

on:
  push:
    branches:
      - main
      - bla/fasel

jobs:
  build:
    name: Build - just hello world.
    runs-on: ubuntu-latest
    
    steps:
      - name: first step
      - run: echo "Hello world!"


  other_job:
    name: with spaces
    runs-on: ubuntu-latest
    steps:
      - run: echo "my other job"
