name: Wolfram's workflow

on:
  push:
    branches:
      - main
      - bla/fasel
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        type: environment
        required: true
  schedule:
    - cron: "15 6 * * 0"

jobs:
  build:
    name: Build - just hello world.
    runs-on: ubuntu-latest
    
    steps:
      -
        name: first step
        run: echo "Hello world! - from the first step"


  other_job:
    name: with spaces
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '${{ toJSON(steps) }}'
          echo '${{ toJSON(runner) }}'
          echo '${{ toJSON(github.api_url) }}'
      - run: |
          cat << EOT >> $GITHUB_STEP_SUMMARY
          ### Hello world! :rocket:
          
          - some
          - stuff
          - in a
          - list
          
          |t1 |h2 |h3 |
          |---|---|---|
          |bla | fasel | x |
          |bla | blubber | x |
          
          The end of text.
          EOT
      - uses: actions/checkout@v3.0.2
      - name: List files in the repository
        run: |
          echo "The repository ${{ github.repository }} contains the following files:"
          tree

