name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: run my container action
      id: hello-action
      uses: ./hello-world-docker-action
      with:
        who-to-greet: '@Wolfram'

    - name: output time set in container
      run: |
        echo "The time was: ${{ steps.hello-action.outputs.time }} when the action said hello"
